### ISSUE TITLE
Tinytag throws UnicodeDecodeError:

### ISSUE THREAD

**Issue by undefinedvalue0103** [devsnd/tinytag#50]
When I tries to get tags of valid OGG file with `tinytag.TinyTag.get(path)`, I got this trace:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/tinytag/tinytag.py", line 120, in get
    tag.load(tags=tags, duration=duration, image=image)
  File "/usr/local/lib/python3.4/dist-packages/tinytag/tinytag.py", line 135, in load
    self._parse_tag(self._filehandler)
  File "/usr/local/lib/python3.4/dist-packages/tinytag/tinytag.py", line 703, in _parse_tag
    self._parse_vorbis_comment(walker)
  File "/usr/local/lib/python3.4/dist-packages/tinytag/tinytag.py", line 737, in _parse_vorbis_comment
    keyvalpair = codecs.decode(fh.read(length), 'UTF-8')
  File "/usr/lib/python3.4/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 10: invalid start byte
```

Python version: `3.4.0 CPython` on `linux`

**Comment by devsnd** [comment]
Hi!

Can you please provide a example file, so i can reproduce the issue?

**Comment by undefinedvalue0103** [comment]
[actor_in_battle_1.ogg.zip](https://github.com/devsnd/tinytag/files/2131165/actor_in_battle_1.ogg.zip)

**Comment by devsnd** [comment]
Hey @undefinedvalue0103,

I took a look at the file, and the meta-data of the file does to be corrupt (the audio data is okay though). I will make it so that TinyTag does not crash when parsing such files.

**Comment by devsnd** [comment]
The change will be released in the next version (something bigger than 0.19.0)
