### ISSUE TITLE
AssertionError: tinytag .dist-info directory not found

### ISSUE THREAD

**Issue by aruna09** [devsnd/tinytag#71]
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py", line 919, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/req/req_install.py", line 445, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/wheel.py", line 391, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: tinytag .dist-info directory not found
 
This is the full issue log. Any packages that I may be missing?

**Comment by devsnd** [comment]
Tinytag does not have any dependencies. What is the command that results in
this output?

**Comment by aruna09** [comment]
Was just trying to build a tool made by someone else. Cant share much as the repo is still private. Anything else that you can think of could lead to a error like this?

**Comment by devsnd** [comment]
Sorry, without any info i cant help you!

**Comment by tobinus** [comment]
I stumbled over this error as well, but only on Python version 3.3 (while the original poster seems to be using 3.5). I do not see any error with the same requirements.txt on 2.7, 3.4, 3.5 and 3.6.

It seems to be an error with the wheel, since it works perfectly when I disabled the usage of binary by adding `--no-binary tinytag` to my `pip` command, e.g.:

```bash
pip install --no-binary tinytag tinytag
```

Here is the log of a terminal session where I first try to install tinytag naively, and then install it without using the binary. I am using Pyenv together with a virtualenv to get an isolated environment with Python 3.3, on Ubuntu 18.04.

```bash
$ python --version
Python 3.3.6
$ pip --version
pip 10.0.1 from /home/blabla/.pyenv/versions/3.3.6/envs/testing-3.3/lib/python3.3/site-packages/pip (python 3.3)
$ pip freeze
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
$ pip install tinytag
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Collecting tinytag
Installing collected packages: tinytag
Exception:
Traceback (most recent call last):
  File "/home/blabla/.pyenv/versions/3.3.6/envs/testing-3.3/lib/python3.3/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/blabla/.pyenv/versions/3.3.6/envs/testing-3.3/lib/python3.3/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/home/blabla/.pyenv/versions/3.3.6/envs/testing-3.3/lib/python3.3/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/blabla/.pyenv/versions/3.3.6/envs/testing-3.3/lib/python3.3/site-packages/pip/_internal/req/req_install.py", line 748, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/blabla/.pyenv/versions/3.3.6/envs/testing-3.3/lib/python3.3/site-packages/pip/_internal/req/req_install.py", line 961, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/blabla/.pyenv/versions/3.3.6/envs/testing-3.3/lib/python3.3/site-packages/pip/_internal/wheel.py", line 316, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: tinytag .dist-info directory not found
$ pip freeze
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
UNKNOWN==1.2.2
$ pip uninstall UNKNOWN
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Uninstalling UNKNOWN-1.2.2:
  Would remove:
    /home/blabla/.pyenv/versions/3.3.6/envs/testing-3.3/lib/python3.3/site-packages/UNKNOWN-1.2.2.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled UNKNOWN-1.2.2
$ pip freeze
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
$ pip install --no-binary tinytag tinytag
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Collecting tinytag
  Using cached https://files.pythonhosted.org/packages/38/34/e143d21a8ebea99c8af554a3e8978ad08469f1b093762346c9ca0296ebb4/tinytag-1.2.2.tar.gz
Skipping bdist_wheel for tinytag, due to binaries being disabled for it.
Installing collected packages: tinytag
  Running setup.py install for tinytag ... done
Successfully installed tinytag-1.2.2
$ pip freeze
DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
tinytag==1.2.2
```

**Comment by tobinus** [comment]
Correction: This occurs for me when using pyenv with locally built Python versions (installed with pyenv), but not for the Python that was distributed with my Ubuntu. That is, I encountered this with Python version 3.4 as well.
